# Created in Python 3.5
print (' ____                      ')
print ('|  __|                     ')
print ('| |__    _  __      ___     ___')
print ('|  __|  | |/__\    / _ \   / _ \ ')
print ('| |     |  /  \/  | / \ | | / \ |')
print ('| |     | |       | \_/ | | \_/ | ')
print ('|_|     |_|        \___/   \___ |')
print ('  CARDS                       | |')
print ('  By Sean E.             /\   | |  ') 
print ('                         \ \__/ /')
print ('                          \____/')
